### ISSUE TITLE
__init__() got an unexpected keyword argument 'loss'

### ISSUE THREAD

**Issue by Naf27** [A-Stangeland/SolarDetection#8]
Hello, 
I have got : __init__() got an unexpected keyword argument 'loss' when runing the model trainnig 
"""
:ETA: 0s - loss: 0.0102 - accuracy: 0.9959 - PR_AUC: 0.9915 - precision: 0.9568 - recall: 0.94455/455 [==============================] - 2362s 5s/step - loss: 0.0102 - accuracy: 0.9959 - PR_AUC: 0.9915 - precision: 0.9568 - recall: 0.9484 - val_loss: 0.0086 - val_accuracy: 0.9966 - val_PR_AUC: 0.9937 - val_precision: 0.9670 - val_recall: 0.9543
Traceback (most recent call last):
  File "D:\1_clients\2_sde_03\SolarDetection_project\INSA_Project\SolarDetection-main\train_unet.py", line 155, in <module>
    main()
  File "D:\1_clients\2_sde_03\SolarDetection_project\INSA_Project\SolarDetection-main\train_unet.py", line 142, in main
    model, training_history = train_unet(**training_parameters)
  File "D:\1_clients\2_sde_03\SolarDetection_project\INSA_Project\SolarDetection-main\train_unet.py", line 88, in train_unet
    training_history_df = pd.DataFrame(**training_history.history)
TypeError: __init__() got an unexpected keyword argument 'loss'
###

**Comment by A-Stangeland** [comment]
Hi,
The error should be fixed now.
